Enhancement: Add description and cause to gRPC status when exception occured (RP-1636)
Before:
```
Rpc failed with status code 2, error message:
```

After:
```
Rpc failed with status code 2, error message: my exception
```

Logs:
```
2020-05-28 20:42:41.215  WARN [governance,6bba1d2404bc3fd4,6bba1d2404bc3fd4,false] 30041 --- [ault-executor-0] GlobalExceptionHandlingServerInterceptor : Exception occurred while processing gRPC request.

java.lang.RuntimeException: my exception
	at com.silenteight.serp.governance.bulkchange.ValidateBulkChangeUseCase.activate(ValidateBulkChangeUseCase.java:31)
	at com.silenteight.serp.governance.bulkchange.BulkChangeFacade.validateBulkBranchChange(BulkChangeFacade.java:41)
	at com.silenteight.serp.governance.bulkchange.grpc.BulkBranchChangeGrpcService.validateBulkChange(BulkBranchChangeGrpcService.java:26)
	at com.silenteight.proto.serp.v1.api.BulkBranchChangeGovernanceGrpc$MethodHandlers.invoke(BulkBranchChangeGovernanceGrpc.java:286)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at com.silenteight.sep.base.common.grpc.GlobalExceptionHandlingServerInterceptor$1.onHalfClose(GlobalExceptionHandlingServerInterceptor.java:41)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at com.silenteight.sep.base.common.grpc.GlobalExceptionHandlingServerInterceptor$1.onHalfClose(GlobalExceptionHandlingServerInterceptor.java:41)
	at brave.grpc.TracingServerInterceptor$ScopingServerCallListener.onHalfClose(TracingServerInterceptor.java:159)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:817)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Reviewed-by: Bartosz Martofel <bmartofel@silenteight.com>
Reviewed-by: Andrzej Jaromin <ajaromin@silenteight.com>
Merged from: https://gitlab.silenteight.com/sep/sep-base/-/merge_requests/2