fix: properly annotate deploy notifier SealedSecret; reenable (DOS-892) (#355)
1) make the SealedSecret part of pre-install hook, as the Pod
   in pre-install requires the secret
2) delete the SealedSecret after hook completes; otherwise it gets
   recreated and causes Helm to complain:
Error: secrets "notification-keys" already exists.